version: '3.5'
services:
  ztncui:
    image: keynetworks/ztncui
    container_name: ztncui
    restart: unless-stopped
    ports:
      - 9993:9993
      - 9993:9993/udp
      - 3443:3443
    volumes:
      - ./data/zerotier:/var/lib/zerotier-one
      - ./data/ztncui:/opt/key-networks/ztncui/etc
    environment:
      - ENDPOINT=${ZTNCUI_ENDPOINT:-localhost/9993}
      - HTTPS_PORT=3443
      - HTTP_ALL_INTERFACES=yes
      - ZTNCUI_PASSWD=${ZTNCUI_PASSWORD:-ztncui}
    profiles:
      - vpn

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ${JELLYFIN_CONFIG:-./data/jellyfin}:/config
      - ${JELLYFIN_MEDIA:-/data/media}:/data
    ports:
      - 8096:8096
    restart: unless-stopped
    profiles:
      - jellyfin
      - media

  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: ${LABRY_POSTGRES_DB:-labry}
      POSTGRES_USER: ${LABRY_POSTGRES_USER:-labry}
      POSTGRES_PASSWORD: ${LABRY_POSTGRES_PASSWORD:-labry}
    volumes:
      - ../configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${LABRY_POSTGRES_DATA:-./data/postgres}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    profiles:
      - db
      - database
      - postgres

  gogs:
    image: gogs/gogs
    ports:
      - 2222:22
      - 3000:3000
    volumes:
      - ${LABRY_GOGS_DATA:-./data/gogs}:/data
    profiles:
      - git
      - gogs

  jupyter:
    image: jupyterhub/jupyterhub
    container_name: jupyter
    ports:
      - 15751:8000
      - 15752:8081
    profiles:
      - jupyter
      - notebook

  spdf:
    image: frooodle/s-pdf:latest
    ports:
      - 12621:8080
    volumes:
      - ./data/spdf:/usr/share/tesseract-ocr/5/tessdata
      - ./configs/spdf:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false

  caddy:
    image: caddy:2
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./configs/caddy:/config/caddy
      - ./data/caddy:/data/caddy
    ports:
      - 80:80
      - 443:443

networks:
  labry: